### ISSUE TITLE
BUG : publisher_metadata.plos_dc_date

### ISSUE THREAD

**Issue by patt0** [SavinaRoja/OpenAccess_EPUB#6]
Some articles in PLOS may not have history node while they have pub_date node in which case the execution flow exits prematurely.

date_list = []
history = article.metadata.front.article_meta.history
if history is None:
    return date_list
....

**Comment by SavinaRoja** [comment]
Could you name a PLoS article DOI with that condition so I can test it?  Also, try using the https://github.com/SavinaRoja/OpenAccess_EPUB/tree/iss6 branch and see if it fixes the problem. Did OAE exit entirely or was it simply missing the pub_date node information (which is what I think the issue was)?

**Comment by patt0** [comment]
Hello Paul,

Thanks for your reply.
1. I would expect that you are right and that execution would not stop
   entirely.
2. I spotted the bug by looking at the code, not by running it and getting
   an error. I was running a routine to produce some metadata.

An example of a doi which produces the bug is
: 10.1371/journal.pbio.1001240

By opposition 10.1371/journal.pbio.1001465 has a <history>

The bug is observable when we look at the .opf file for the particular
article, the first will not have a dc:date tag, while the other will

i.e. <dc:date opf:event="publication">2013-1-8/dc:date<dc:date
opf:event="creation">2012-11-16/dc:date
1. Yes after updating your patch, we get a better result in the .opf file

<dc:date opf:event="publication">2012-1-10/dc:date
1. Further I am going through a batch exercise and am finding quite a
   number of doi's in error.

My team is working to classify errors and identify root causes.

If you like, I will be happy to share these with you over the coming weeks.
1. I am slowly getting familiar with the code base and would love to see
   how I could contribute under your guidance.

In particular how we can get this to produce EPUB 3  documents from OA XML.

Patrick Martinent
+919840808693

**Comment by SavinaRoja** [comment]
I would quite appreciate some collaborative effort on this project. Some months ago I acquired a nearly complete PLoS corpora along with images so I could run such tests, but a full batch run on the corpora was very slow on my hardware. I'm very interested in your team's results and would be happy to work with you to improve the project.

EPUB3 has been a goal of mine for some time, and I think it will take relatively little work to implement alongside EPUB2. I'll do some thinking about how to organize this.

I'll make a few notes about the forms errors may take  as I have become familiar with them. Some errors occur during article parsing due to bad formatting of the XML, others may not pass validation according to their tag set specification (there is an option to ignore this, but it's risky); these are the domain of the publisher. Other errors are in the project's domain. Some errors are due to bugs in my code which are only exposed on certain content structures. There may also be what I call "errors of omission", which is when some part of an article's content does not get carried into the EPUB. This is usually because an article uses a rare kind of content which I have not created a handler for yet; this is a tricky kind of error because it usually does result in a raised exception or an error during epubcheck validation. It may also be possible to get a false-negative result from epubcheck during validation, but should be rare.

**Comment by patt0** [comment]
Wonderful,

I look forward to working with you on this over the next few months.

Best

Patrick Martinent
+919840808693

**Comment by patt0** [comment]
Would you be kind enough to share your email address so I can share a google spreadsheet where are consolidating the results of our conversion effort.  We have a couple of wide reaching issues already and will also be adding the entire list of articles in exception, journal by journal over the next week.

**Comment by SavinaRoja** [comment]
Sure thing: pablo.barton@gmail.com

**Comment by SavinaRoja** [comment]
I'm going to go ahead and close this issue. I've got onto the spreadsheet. I recommend that you and your team submit any and all pull requests you desire, it is the fastest way for me to work on and implement solutions. Opening new issues on the project is also welcome.
